### PR TITLE
Maven version 3.3.9

### PR DESCRIPTION
**Pull request by jpmat296**
Here is PR with changes:
- Update to Maven version 3.3.9
- Change URL to official apache URL used by 'ant' package too

HTH
Jean-Pierre

### CODE REVIEW

**Comment by MichaelPereira** [comment]
Thanks for the change, I will re-setup my machine to upload it today.

**Comment by jpmat296** [comment]
Welcome. But when the new version will be available on chocolatey.org [here](https://chocolatey.org/packages/maven) ?

**Comment by MichaelPereira** [comment]
@jpmat296 I've just uploaded the package. It will be available at https://chocolatey.org/packages/maven/3.3.9 once approved by the moderation team.

**Comment by jpmat296** [comment]
Package was rejected by choco reviewer. More info in PR #6.

**Pull request merged**
