### PR TITLE
Update to Maven 3.5.3

### PR DESCRIPTION
**Pull request by davidsan**
Updated for Maven 3.5.3

### CODE REVIEW

**Comment by aaccioly** [comment]
Looks ok to me

**Comment by MichaelPereira** [comment]
Thanks for the change @davidsan, once again I will have to let someone else (@aaccioly ?) publish it as I don't have a Windows environment to build it anymore

**Comment by aaccioly** [comment]
Hi @MichaelPereira, merge it and I'll publish it (or do you prefer me to publish it before merging)?

**Comment by aaccioly** [comment]
Ops, sorry, just realised that it has been merged already. I'll publish it.

**Comment by aaccioly** [comment]
Just pushed the new version: https://chocolatey.org/packages/maven/3.5.3

**Pull request merged**
