### PR TITLE
Update to Maven 3.6.3.

### PR DESCRIPTION
**Pull request by nickstolwijk**

### CODE REVIEW

**Review by MichaelPereira — APPROVED** [review]
Looks good!

**Comment by nickstolwijk** [comment]
Thanks. Do I need to do anything now? I'm new to Chocolatey packages and PR's to this repository.

**Comment by aaccioly** [comment]
Hey @nickstolwijk , you did great. I'll merge and publish it first thing tomorrow morning, let me just do some corner case testing first (non-related with your changes, just something that will be released with it). If you are interested in becoming a packager maintainer let me know. Either Michael or myself can grant you access to publish the package.

**Comment by nickstolwijk** [comment]
I follow the Maven mailing list pretty active. If all it takes is changing the version numbers and the hash I think I can make the Maven releases available on Chocolatey on the day of the releases of Maven.

I also have some ideas, like changing the name to Maven3, knowing that the Maven community is thinking about starting on a Maven 4 with huge changes. So people should start choosing Maven 3 or Maven 4, whenever it will be out.

Is there a way to also have RC's of Maven distributed by Chocolatey, only by choice?

And if you think I will mess up, I am also willing to do the coming releases as PR's.

**Comment by MichaelPereira** [comment]
I unfortunately don't have the environment available anymore to publish packages myself :(

Once chocolatey is back to working(https://status.chocolatey.org/), we can add you as a maintainer

**Comment by aaccioly** [comment]
Hi guys,

Sorry, I couldn't get to test everything yet, will do it tonight for sure.
I'll publish myself this evening if no further changes becomes necessary.

Feel free to create a user on Chocolatey if you haven't already done so. I
can help you setup your local environment and push packages (if you want we
can have a call). Your help is much appreciated and the community will
certainly benefit from faster releases.

I'm now fixing multi-version installs and in the future we can always put
some effort to make it an autopackage :).

Kind regards,
---
Anthony Accioly

**Comment by aaccioly** [comment]
Merged and published. Chocolatey main website is still a little bit shaky but hopefully it will soon pass automated review. @nickstolwijk , thanks again for your help and feel free to ping me your chocolatey username to become a package maintainer.

**Pull request merged**
