### PR TITLE
Update Maven to 3.3.3

### PR DESCRIPTION
**Pull request by joelhandwell**

### CODE REVIEW

**Comment by MichaelPereira** [comment]
Thanks for the PR, I will try to remember to merge and update the package tonight,

**Comment by joelhandwell** [comment]
@MichaelPereira any update ?

**Comment by joelhandwell** [comment]
@MichaelPereira let me write reminder.

**Comment by MichaelPereira** [comment]
The updated package was uploaded https://chocolatey.org/packages/maven/3.3.3

**Comment by joelhandwell** [comment]
@MichaelPereira Thank you!

**Pull request merged**
