### PR TITLE
Update maven to 3.6.1

### PR DESCRIPTION
**Pull request by FrankDeGroot**
I've updated this version #s and download hash for Maven to 3.6.1 in lieu to the update to 3.6.0.
Let me know if I missed something.

### CODE REVIEW

**Comment by aaccioly** [comment]
Looks good to me.
Have you built and installed it locally to make sure that everything is working?

    choco pack
    choco install packageFile -dv -s .

**Comment by FrankDeGroot** [comment]
Yes, it's working.
It does appear that a `choco update` won't delete the previous version but I think that it's not caused by this change.

**Comment by flatmapthatshit** [comment]
Yeahp, I noticed the left overs in previous versions
I'm meginf your changes. @MichaelPereira, @jpmat272, can one of you publish it to chocolatey?

**Comment by aaccioly** [comment]
Yeahp, I noticed the left overs in previous versions, it is certainly not a new issue.
I'm merging your changes. @MichaelPereira, @jpmat296, can one of you publish the new version to chocolatey?

**Comment by jpmat296** [comment]
Thanks a lot both for your contribution.

@aaccioly What do you need to publish yourself the new version ? Are you still not maintainer ?

**Comment by aaccioly** [comment]
@jpmat296 , other than a second set of eyes (and someone to share the blame :D), nothing really.
I've just pushed the package.

**Comment by MichaelPereira** [comment]
Changes look good, thanks everyone 👍

**Pull request merged**
