### PR TITLE
Updating Flyway to version 3.1

### PR DESCRIPTION
**Pull request by mjiderhamn**

### CODE REVIEW

**Comment by mjiderhamn** [comment]
Sorry, realized you were not the primary maintainer of this.
For reference I created https://github.com/adorepump/chocolatey-packages/pull/28 instead.

**Comment by MichaelPereira** [comment]
Well, the primary maintainer seems to have abandonned it too, given the number of open merge request, I don't mind letting you use this repository.

You should contact the chocolatey admins to get maintainer status on this package as the original maintainer is inactive

**Comment by RehanSaeed** [comment]
This package has been abandoned and is now pretty ancient. +1 for @mjiderhamn to be given maintainer status.

**Comment by MichaelPereira** [comment]
I don't mind if you want to use this repo to update the package @mjiderhamn

**Comment by ferventcoder** [comment]
@mjiderhamn @RehanSaeed have either of you reached out to the site admins on Chocolatey.org and asked to become maintainers? https://chocolatey.org/docs/package-triage-process#the-triage-process

**Pull request closed without merging**
